"""empty message

Revision ID: 1b59c4854ca1
Revises: 70d95c144625
Create Date: 2018-12-26 11:59:08.041089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b59c4854ca1'
down_revision = '70d95c144625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cate__business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('business', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('type', mysql.VARCHAR(length=16), nullable=True))
    op.drop_table('cate__business')
    # ### end Alembic commands ###
