"""empty message

Revision ID: 8b0c133334fe
Revises: 1b59c4854ca1
Create Date: 2018-12-26 12:02:43.105390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0c133334fe'
down_revision = '1b59c4854ca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('type', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'business', 'cate__business', ['type'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'business', type_='foreignkey')
    op.drop_column('business', 'type')
    # ### end Alembic commands ###
