"""empty message

Revision ID: de8d3048e145
Revises: ef16a709aadf
Create Date: 2018-12-24 22:57:35.345099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8d3048e145'
down_revision = 'ef16a709aadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('business', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business'], ['business.id'], ),
    sa.ForeignKeyConstraint(['category'], ['pro_cate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
